# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('account_slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
