# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
