# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
