# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
