# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161121_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_slug',
            field=models.SlugField(default='test_user', unique=True),
            preserve_default=False,
        ),
    ]
