# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161118_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
