# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_auto_20170425_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
